spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
        - id: shop
          uri: lb://shop
          predicates:
            - Path=/shop/**
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"





